In [8]:
from timeit import timeit
import numpy as np

a = np.arange(100000).reshape(100, 100, 10).swapaxes(0, 1)
a

array([[[    0,     1,     2, ...,     7,     8,     9],
        [ 1000,  1001,  1002, ...,  1007,  1008,  1009],
        [ 2000,  2001,  2002, ...,  2007,  2008,  2009],
        ...,
        [97000, 97001, 97002, ..., 97007, 97008, 97009],
        [98000, 98001, 98002, ..., 98007, 98008, 98009],
        [99000, 99001, 99002, ..., 99007, 99008, 99009]],

       [[   10,    11,    12, ...,    17,    18,    19],
        [ 1010,  1011,  1012, ...,  1017,  1018,  1019],
        [ 2010,  2011,  2012, ...,  2017,  2018,  2019],
        ...,
        [97010, 97011, 97012, ..., 97017, 97018, 97019],
        [98010, 98011, 98012, ..., 98017, 98018, 98019],
        [99010, 99011, 99012, ..., 99017, 99018, 99019]],

       [[   20,    21,    22, ...,    27,    28,    29],
        [ 1020,  1021,  1022, ...,  1027,  1028,  1029],
        [ 2020,  2021,  2022, ...,  2027,  2028,  2029],
        ...,
        [97020, 97021, 97022, ..., 97027, 97028, 97029],
        [98020, 98021, 98022, ..., 98027, 980

In [9]:
a.ravel(order='C')

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [10]:
a.ravel(order='K')

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [15]:
timeit("a.ravel(order='C')", globals = {'a': a})

99.7905829

In [16]:
timeit("a.ravel(order='A')", globals = {'a': a})

91.62753620000001

In [16]:
import numpy as np
import gym
env = gym.make('CartPole-v0')
obs = env.reset()
type(obs)

numpy.ndarray

In [14]:
import tensorflow as tf
tf.random.uniform([1, 1]) > 0.5

<tf.Tensor: shape=(1, 1), dtype=bool, numpy=array([[False]])>